FROM krlmlr/debian-ssh

#RUN apt-get install -y sudo net-tools wget sysvinit-core sysvinit \
#                       sysvinit-utils curl vim man faketime unzip \
#                       iptables iputils-ping logrotate && \
#    apt-get remove -y --purge --auto-remove systemd

EXPOSE 22

CMD sleep 999
