version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
       POSTGRES_PASSWORD: palantir
       POSTGRES_USER: palantir
       POSTGRES_DB: atlas
    ports:
      - "5432"

  ete1:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.dbkvs.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://postgres:5432 && service/bin/init.sh console'
    depends_on:
      - postgres
    environment:
      - ME=ete1
    ports:
      - "3828"

  ete2:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.dbkvs.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://postgres:5432 && service/bin/init.sh console'
    depends_on:
      - postgres
    environment:
      - ME=ete2
    ports:
      - "3828"

  ete3:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.dbkvs.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://postgres:5432 && service/bin/init.sh console'
    depends_on:
      - postgres
    environment:
      - ME=ete3
    ports:
      - "3828"

  ete-cli:
    build: .
    entrypoint: [bash, -c, 'cp var/conf/atlasdb-ete.dbkvs.yml var/conf/atlasdb-ete.yml && "$$@"', --]
    command: exit
    environment:
      - ME=ete1
    depends_on:
      - ete1
