version: '2'

services:
  cassandra:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    ports:
      - "9160"
      - "9042"
      - "7199"
    environment:
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  ete1:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra-async.yml var/conf/atlasdb-ete.yml && tail -F var/log/atlasdb-ete-startup.log'
    environment:
      - ME=ete1
    ports:
      - "3828"

  ete2:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra-async.yml var/conf/atlasdb-ete.yml && tail -F var/log/atlasdb-ete-startup.log'
    environment:
      - ME=ete2
    ports:
      - "3828"

  ete3:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra-async.yml var/conf/atlasdb-ete.yml && tail -F var/log/atlasdb-ete-startup.log'
    environment:
      - ME=ete3
    ports:
      - "3828"
