version: '2'

services:
  cassandra:
    image: com.palantir.docker/atlas-cassandra:2.2-v0.1
    ports:
      - "9160"
      - "9042"
      - "7199"
    environment:
      - LOCAL_JMX=no

  ete1:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://cassandra:9160 && service/bin/init.sh console'
    environment:
      - ME=ete1
    ports:
      - "3828"

  ete2:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://ete1:3828 && service/bin/init.sh console'
    environment:
      - ME=ete2
    depends_on:
      - ete1

  ete3:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.cassandra.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://ete1:3828 && service/bin/init.sh console'
    environment:
      - ME=ete3
    depends_on:
      - ete1
