version: '2'

services:
  cassandra1:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  cassandra2:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  cassandra3:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  ete1:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.multiple-cassandra.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://cassandra1:9160 -wait tcp://cassandra2:9160 -wait tcp://cassandra3:9160 && service/bin/init.sh console'
    environment:
      - ME=ete1
    ports:
      - "3828"

  ete-cli:
    build: .
    entrypoint: [bash, -c, 'cp var/conf/atlasdb-ete.multiple-cassandra.yml var/conf/atlasdb-ete.yml && "$$@"', --]
    command: exit
    environment:
      - ME=ete1
    depends_on:
      - ete1
