services:
  oracle:
    image: palantirtechnologies/oracle-atlasdb:19.24.0.0
    ports:
      - "1521"
    environment:
      ORACLE_SYS_PASSWORD: 7_SeeingStones_7
      MEMORY: 2Gi

  ete1:
    build: .
    command: [bash, -c, 'cp var/conf/atlasdb-ete.embedded-and-oracle.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://oracle:1521 && service/bin/init.sh console']
    ports:
      - "3828"
    depends_on:
      - oracle
    environment:
      - ME=ete1
