version: '2'

services:
  oracle:
    image: palantirtechnologies/oracle-atlasdb:19.20.0.0-se
    ports:
      - "1521"

  ete1:
    build: .
    command: [bash, -c, 'cp var/conf/atlasdb-ete.embedded-and-oracle.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://oracle:1521 && service/bin/init.sh console']
    ports:
      - "3828"
    depends_on:
      - oracle
    environment:
      - ME=ete1
