# if you're editing this file, codecov has an endpoint exposed to let you validate it before you commit (it will fail silently otherwise if you make a mistake)
# curl --data-binary @.codecov.yml https://codecov.io/validate

ignore: 
  - "examples/" # just example usage, not part of library to be tested
  - "atlasdb-ete-tests/" # these run in docker containers so they're not tracked
  - "atlasdb-exec/src/main/java/com/palantir/atlasdb/clis/RegenerateCodeForSchemas.java" # only run by devs in IDE
  - "cassandra-partitioner/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/dht/AtlasDbOrderedPartitioner.java" # only here for documentation
  - "atlasdb-perf/" # benchmarks that are run separately
