FROM anapsix/alpine-java

RUN apk update && apk add openssl openssh

COPY id_rsa id_rsa.pub /root/.ssh/
COPY project.clj /

RUN wget https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein && \
    mv /lein /usr/bin && \
    chmod +x /usr/bin/lein && \
    lein install && \
    rm project.clj

COPY initialize_known_hosts.sh /usr/bin
