CREATE USER palantir IDENTIFIED BY palpal QUOTA UNLIMITED ON users;

GRANT
    CREATE SESSION,
    CREATE PROCEDURE,
    CREATE SEQUENCE,
    CREATE TABLE,
    CREATE VIEW,
    CREATE TYPE
TO palantir;
