version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: palantir
      POSTGRES_USER: palantir
      POSTGRES_DB: atlas
    ports:
      - "5432:5432"
