server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

atlasdb:
  keyValueService:
    type: relational
    ddl:
      type: postgres
    connection:
      type: postgres
      host: postgres
      port: 5432
      dbName: atlasete
      dbLogin: palantir
      dbPassword: palantir
      sslmode: require
