server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

atlasdb:
  keyValueService:
    type: cassandra
    servers:
      - cassandra:9160
    poolSize: 20
    keyspace: atlasete
    credentials:
      username: cassandra
      password: cassandra
    ssl: false
    replicationFactor: 1
    mutationBatchCount: 10000
    mutationBatchSizeBytes: 10000000
    fetchBatchCount: 1000
    safetyDisabled: false
    autoRefreshNodes: false

  leader:
    quorumSize: 2
    learnerLogDir: var/data/paxosLog/learner1
    acceptorLogDir: var/data/paxosLog/acceptor1
    localServer: http://${ME}:3828
    leaders:
      - http://ete1:3828
      - http://ete2:3828
      - http://ete3:3828
